project 'JPVideoPlayerDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform:ios,'8.0'

target 'JPVideoPlayerDemo' do
 use_frameworks!
 pod 'Masonry'
 pod 'JPNavigationController', '~> 2.1.3'
end
